Topic 1.1 : Loaders fetchers and generators

In [23]:
from sklearn.datasets import load_iris
data = load_iris()

from sklearn.datasets import load_diabetes
data2 = load_diabetes()

from sklearn.datasets import load_digits
data3 = load_digits()

from sklearn.datasets import load_wine
data4 = load_wine()

from sklearn.datasets import load_breast_cancer
data5 = load_breast_cancer()

from sklearn.datasets import load_linnerud
data6 = load_linnerud()

In [24]:
X, y = load_iris(return_X_y = True, as_frame = True)

In [25]:
?load_iris

In [26]:
?load_digits

In [27]:
x, y = load_digits(return_X_y = True, as_frame = True)

In [28]:
x.shape

(1797, 64)

In [29]:
y.shape

(1797,)

In [30]:
from sklearn.datasets import fetch_california_housing
data7 = fetch_california_housing()

In [31]:
data7.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [32]:
data7.target_names

['MedHouseVal']

In [33]:
from sklearn.datasets import fetch_openml
X, y = fetch_openml('mnist_784', version = 1, return_X_y = True)

/usr/local/lib/python3.9/dist-packages/sklearn/datasets/_openml.py:932: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [34]:
from sklearn.datasets import fetch_20newsgroups
fetched = fetch_20newsgroups(subset = 'train')


In [35]:
from sklearn.datasets import fetch_kddcup99

In [36]:
from sklearn.datasets import load_breast_cancer
data10 = load_breast_cancer()

In [37]:
x, y = load_breast_cancer(return_X_y = True, 
                          as_frame = True)

In [38]:
x.shape

(569, 30)

In [39]:
y.shape

(569,)

In [40]:
data10.target_names

array(['malignant', 'benign'], dtype='<U9')

In [41]:
import numpy as np
len(np.where(y == 0)[0])

212

In [42]:
y.shape

(569,)

In [43]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [44]:
from scipy.stats import pearsonr
pearsonr(x['mean perimeter'],x['mean radius'])

PearsonRResult(statistic=0.9978552814938108, pvalue=0.0)

In [45]:
mat =  [[7, 16, 31], [np.nan, np.nan, 66], [12, 5, np.nan],[98, np.nan, 92]]

In [46]:
mat

[[7, 16, 31], [nan, nan, 66], [12, 5, nan], [98, nan, 92]]

In [47]:
from sklearn.impute import SimpleImputer

In [52]:
imputer = SimpleImputer(strategy = 'mean')

In [53]:
imputer.fit(mat)

SimpleImputer()

In [54]:
imputer.statistics_

array([39. , 10.5, 63. ])

In [55]:
mat_tr = imputer.transform(mat)

In [56]:
mat_tr

array([[ 7. , 16. , 31. ],
       [39. , 10.5, 66. ],
       [12. ,  5. , 63. ],
       [98. , 10.5, 92. ]])

In [57]:
mat2 = np.array([[1, 1], [2, 3],[10,100]]) 

from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.log10)

transformer.transform(mat2)

array([[0.        , 0.        ],
       [0.30103   , 0.47712125],
       [1.        , 2.        ]])