In [4]:
# dictvectorizer Illustration

data = [{'age':4, 'height':96},{'age':5,'height':101}]

from sklearn.feature_extraction import DictVectorizer
df = DictVectorizer(sparse = False)
new = df.fit_transform(data)

In [7]:
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", 
                   names = ['sepal length', 'sepal width', 'petal length', 'petal width','label'])

In [14]:
data

sepal length  sepal width  petal length  petal width           label
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [21]:
new_df = data[['sepal length', 'sepal width', 'petal length', 'petal width']]
new_df

sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [22]:
from sklearn.preprocessing import PolynomialFeatures
transformer = PolynomialFeatures(degree = 2)
data_tr = transformer.fit_transform(new_df)

In [23]:
data_tr.shape

(150, 15)

In [29]:
# variance threshold

from sklearn.feature_selection import VarianceThreshold
X = [[0, 2, 0, 3], [0, 1, 4, 3], [0, 1, 1, 3]]
selector = VarianceThreshold()
final = selector.fit_transform(X)
final

array([[2, 0],
       [1, 4],
       [1, 1]])

In [31]:
selector.get_params

<bound method BaseEstimator.get_params of VarianceThreshold()>

In [33]:
import numpy as np

a = np.arange(24)

print(a)
# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

print(a.shape)
# (24,)

print(a.ndim)
# 1

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
1


In [34]:
a.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [35]:
from sklearn.datasets import fetch_california_housing
x,y = fetch_california_housing(return_X_y = True, as_frame = True)

In [36]:
x.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [37]:
y.head()

0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: MedHouseVal, dtype: float64

In [44]:
from sklearn.feature_selection import GenericUnivariateSelect, mutual_info_regression
selector = GenericUnivariateSelect(mutual_info_regression, 
                                   mode = 'percentile',param = 0.10)
xnew = selector.fit_transform(x,y)


In [45]:
xnew.shape

(20640, 1)

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                                    test_size = 0.2 )

In [48]:
x_train.shape

(16512, 8)

In [49]:
from sklearn.dummy import DummyRegressor


In [56]:
regressor = DummyRegressor(strategy = 'mean')

In [57]:
regressor.fit(x_train,y_train)

DummyRegressor()

In [58]:
y_pred = regressor.predict(x_test)

In [59]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.0007655950493239416

In [60]:
y_train.mean()

2.0748590491763563

In [61]:
y_train

14057    1.688
15450    2.390
6583     4.508
2907     1.266
11108    2.730
         ...  
7911     1.460
193      1.125
11833    1.413
14193    1.414
5716     3.063
Name: MedHouseVal, Length: 16512, dtype: float64

In [62]:
y_new = y_train.copy()

In [66]:
y_new = pd.DataFrame(y_new)

In [67]:
y_new

MedHouseVal
14057     1.688000
15450     2.390000
6583      4.508000
2907      1.266000
11108     2.730000
...            ...
193       1.125000
11833     1.413000
14193     1.414000
5716      3.063000
mean      2.074859

[16513 rows x 1 columns]

In [68]:
y_new['mean'] = y_train.mean()

In [69]:
y_new

MedHouseVal      mean
14057     1.688000  2.074859
15450     2.390000  2.074859
6583      4.508000  2.074859
2907      1.266000  2.074859
11108     2.730000  2.074859
...            ...       ...
193       1.125000  2.074859
11833     1.413000  2.074859
14193     1.414000  2.074859
5716      3.063000  2.074859
mean      2.074859  2.074859

[16513 rows x 2 columns]

In [72]:
r2_score(y_new['MedHouseVal'], y_new['mean'])

-2.220446049250313e-16