**Numpy**

In [2]:
import numpy as np

In [3]:
# Python list is linked list
# numpy array is written in C and thus elements are stored in consequtive memory location

In [4]:
# this is an example of scalar

x = np.array(1)
print(x,'\t',x.ndim,'\t',x.size,'\t',x.shape)

1 	 0 	 1 	 ()


In [5]:
# This is an example of sequence

x = np.array([1,2,3])
print(x,'\t',x.ndim,'\t',x.size,'\t',x.shape)

[1 2 3] 	 1 	 3 	 (3,)


In [ ]:
# size = number of elements
# shape (number of elements in first dimension, )
# one dimension == Sequence
# vector has atleast 2 dimensions

In [6]:
# a (row) vector

x = np.array([[1,2,3]])
print(x,'\t',x.ndim,'\t',x.size,'\t',x.shape)

# in this case shape is (1,3) # i.e. axis 0 contain one element and axis 1 contain 3 elements

[[1 2 3]] 	 2 	 3 	 (1, 3)


In [8]:
# a (column) vector

x = np.array([[1],[2],[3]])
print(x,'\t',x.ndim,'\t',x.size,'\t',x.shape)

[[1]
 [2]
 [3]] 	 2 	 3 	 (3, 1)


In [9]:
# a 2 dimensional array

x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x,'\t',x.ndim,'\t',x.size,'\t',x.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 	 2 	 9 	 (3, 3)


In [10]:
# print zeroth element of axis 0
x[0]

array([1, 2, 3])

In [11]:
# print first element of axis 0
x[1]

array([4, 5, 6])

In [14]:
# print zeroth element of axis 0
x[0][0]

1

In [16]:
# Go to all the elements of axis 0 and print first element
x[:,0]

array([1, 4, 7])

In [18]:
# print 0th element of axis 0
x[0,0]

1

In [19]:
x.sum(axis = 0)

array([12, 15, 18])

In [21]:
x.sum(axis = 1)

array([ 6, 15, 24])

In [23]:
# np.zeros

x = np.zeros((3,3))
print(x,'\t',x.ndim,'\t',x.size,'\t',x.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 	 2 	 9 	 (3, 3)


In [25]:
np.zeros_like(x)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.random.seed(42)
print(np.random.randint(0,10,size=(3,3)))

[[6 3 7]
 [4 6 9]
 [2 6 7]]


In [27]:
rand_state = 42
rand_gen = np.random.RandomState(rand_state)
print(rand_gen.randint(0,10,size=(3,3)))

[[6 3 7]
 [4 6 9]
 [2 6 7]]
